// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/multimedia.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInfo) Reset() {
	*x = PostInfo{}
	mi := &file_proto_multimedia_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfo) ProtoMessage() {}

func (x *PostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_multimedia_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfo.ProtoReflect.Descriptor instead.
func (*PostInfo) Descriptor() ([]byte, []int) {
	return file_proto_multimedia_proto_rawDescGZIP(), []int{0}
}

func (x *PostInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_proto_multimedia_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_multimedia_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_proto_multimedia_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	PostId        string                 `protobuf:"bytes,2,opt,name=postId,proto3" json:"postId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_proto_multimedia_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_multimedia_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_proto_multimedia_proto_rawDescGZIP(), []int{2}
}

func (x *FileChunk) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *FileChunk) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type Post struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_proto_multimedia_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_proto_multimedia_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_proto_multimedia_proto_rawDescGZIP(), []int{3}
}

func (x *Post) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Post) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Post) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Post) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_proto_multimedia_proto protoreflect.FileDescriptor

const file_proto_multimedia_proto_rawDesc = "" +
	"\n" +
	"\x16proto/multimedia.proto\x12\x11MultimediaService\"\x1a\n" +
	"\bPostInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1a\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"9\n" +
	"\tFileChunk\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\x12\x16\n" +
	"\x06postId\x18\x02 \x01(\tR\x06postId\"r\n" +
	"\x04Post\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x16\n" +
	"\x06userId\x18\x04 \x01(\tR\x06userId2\xce\x02\n" +
	"\x11MultimediaService\x12P\n" +
	"\x11GetPostMultimedia\x12\x1b.MultimediaService.PostInfo\x1a\x1c.MultimediaService.FileChunk0\x01\x12R\n" +
	"\x13GetUserProfileImage\x12\x1b.MultimediaService.UserInfo\x1a\x1c.MultimediaService.FileChunk0\x01\x12>\n" +
	"\n" +
	"CreatePost\x12\x17.MultimediaService.Post\x1a\x17.MultimediaService.Post\x12S\n" +
	"\x14UploadPostMultimedia\x12\x1c.MultimediaService.FileChunk\x1a\x1b.MultimediaService.PostInfo(\x01B\tZ\a./protob\x06proto3"

var (
	file_proto_multimedia_proto_rawDescOnce sync.Once
	file_proto_multimedia_proto_rawDescData []byte
)

func file_proto_multimedia_proto_rawDescGZIP() []byte {
	file_proto_multimedia_proto_rawDescOnce.Do(func() {
		file_proto_multimedia_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_multimedia_proto_rawDesc), len(file_proto_multimedia_proto_rawDesc)))
	})
	return file_proto_multimedia_proto_rawDescData
}

var file_proto_multimedia_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_multimedia_proto_goTypes = []any{
	(*PostInfo)(nil),  // 0: MultimediaService.PostInfo
	(*UserInfo)(nil),  // 1: MultimediaService.UserInfo
	(*FileChunk)(nil), // 2: MultimediaService.FileChunk
	(*Post)(nil),      // 3: MultimediaService.Post
}
var file_proto_multimedia_proto_depIdxs = []int32{
	0, // 0: MultimediaService.MultimediaService.GetPostMultimedia:input_type -> MultimediaService.PostInfo
	1, // 1: MultimediaService.MultimediaService.GetUserProfileImage:input_type -> MultimediaService.UserInfo
	3, // 2: MultimediaService.MultimediaService.CreatePost:input_type -> MultimediaService.Post
	2, // 3: MultimediaService.MultimediaService.UploadPostMultimedia:input_type -> MultimediaService.FileChunk
	2, // 4: MultimediaService.MultimediaService.GetPostMultimedia:output_type -> MultimediaService.FileChunk
	2, // 5: MultimediaService.MultimediaService.GetUserProfileImage:output_type -> MultimediaService.FileChunk
	3, // 6: MultimediaService.MultimediaService.CreatePost:output_type -> MultimediaService.Post
	0, // 7: MultimediaService.MultimediaService.UploadPostMultimedia:output_type -> MultimediaService.PostInfo
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_multimedia_proto_init() }
func file_proto_multimedia_proto_init() {
	if File_proto_multimedia_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_multimedia_proto_rawDesc), len(file_proto_multimedia_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_multimedia_proto_goTypes,
		DependencyIndexes: file_proto_multimedia_proto_depIdxs,
		MessageInfos:      file_proto_multimedia_proto_msgTypes,
	}.Build()
	File_proto_multimedia_proto = out.File
	file_proto_multimedia_proto_goTypes = nil
	file_proto_multimedia_proto_depIdxs = nil
}
